### ISSUE TITLE
ogonori development

### ISSUE THREAD

**Issue by ernestas-poskus** [quux00/ogonori#1]
Hi @quux00 

Firstly you came up with a cool name :100: for serious technology.

Secondly I would like to help you with development of this package since I have a personal project where I would like to use binary driver instead of REST.

Thirdly how/where can I start ? I see that you have almost no tests, I understand that in early development this is fine but still we should consider that. 

BTW, nice to meet u :hand:

**Comment by quux00** [comment]
Glad you like the name of the project :-)

Thanks for your offer of help.

> I see that you have almost no tests, I understand that in early development this is fine but still we should consider that.

I have tests with high coverage for the low level parts of the functionality that are the foundational parts of the binary protocol.  For this project I see little value in true test-first TDD since I'm largely not in control of what needs to be built - I have to consume what the OrientDB server sends me and that is unfortunately not well documented in a nice RFC.  A fair bit of the OrientDB documentation for the serialization format and binary protocol is missing or wrong (I've already corrected a few points).  So I'm using the top level "client.go" as a working functional test where I add more tests as I add features against a running OrientDB Server (I'm currently running against 2.0.1).

Feel free to add more tests or to help restructure the somewhat ad-hoc client.go test right now.  But I would have a few cautions:

- the API I have so far is a working model only. I may change it, so writing a lot of tightly coupled tests will make for more work in the future.
- I only have a few interfaces defined, so doing "mocks" will be difficult. For example, in some cases I've used bytes.Buffer rather than io.Reader or io.Writer since I wanted the extra functionality
- I may need to add a more powerful bytesBuffer (OrientDB Java client created their own BytesContainer obj) since I'm not especially happy with how I'm currently doing the forward data pointer writes during serialization, but I'm deferring this for the time being.

So for these reasons, writing a lot of unit tests is perhaps best left for later.



> Thirdly how/where can I start ?

A few suggestions that are on the backlog:

- figure out how to map (serialize/deserialize) Go "date" objects (time.Time?) onto the OrientDB DATE and DATETIME types.

- OrientDB has a DECIMAL type which ogonori needs to handle/map onto a Go type. The Java OrientDB client uses the BigDecimal Java class for this. Unfortunately, the Go stdlib includes no BigDecimal implementation - it only has bit.Int and big.Rat (Rational numbers).  A couple people have posted on the go-nuts golang about building a Decimal library.  However, I want to avoid all third party dependencies in ogonori.  So one option is to look at those libraries and steal the subset of code needed to support DECIMAL serialization/deserialization and how we'll represent that type to ogonori users.

- how to serialize / deserialized LINK, LINKLIST, LINKSET and LINKMAP types - I've done no work on these or have little understanding of how they should be represented

- how to map from the ODocument/OField data structures I've created so far to:  JSON (marshal/unmarshal) and user-defined structs.  Again I'm leery of bringing in any 3rd party libraries, so I want to review the right way to do these things

- multiple APIs - my vision for ogonori is that it will support a series of different APIs:

  - database/sql (although I'm finding that it pretty heavily limits the types that it can handle, so not sure if this really viable)
  - I want to review mgo's API and probably build something like it or even directly copy it and make it an de facto standard for Document databases in Go
  - I may want to have an API that matches the Java OrientDB API for DocumentDBs
  - we need a GraphDB API - I may want to have an API that matches the Java OrientDB API for GraphDBs or something else (like Tinkerpop)
  

  
Here's what I'm currently doing:
  
I have very basic SQL Query and SQL INSERT/DELETE Commands working with simple (String-based) params.  Before I dive into adding more here, I put that aside to understand how to write a Go database/sql driver and what types it expects (e.g., for a ResultSet, to use a JDBC term).  I have the first part of that mostly done (only partially published), but I'm very concerned that the database/sql data type pass through is limited to primitive types (int64, float64, etc.), strings and []byte.  Not sure what to do about structs (OrientDB ODocument's).  I ran across this https://github.com/go-cq/cq yesterday and plan to review it for ideas.

Final note - I haven't published any info on how to run the ad-hoc client.go functional test.  I have a OrientDB SQL load script to set up a simple test database.  I'll include that and instructions on how to use it in one of the next commits/pushes.

**Comment by quux00** [comment]
BTW - if you do want to do some work on the binary protocol and de/serialization (serde), I've learned the hard way that you can't really trust the documentation.  The only way to do it is to fire up Eclipse or IntelliJ and step through the Java client code in a debugger and document what is happening.  Also make sure to turn debugging mode on in the server by modifying it's config file:

    <listener protocol="binary" port-range="2424-2430" ip-address="127.0.0.1">
      <parameters>
        <parameter name="network.binary.debug" value="true" />
      </parameters>
    </listener>

**Comment by ernestas-poskus** [comment]
I will review them too might be good for inspiration as well as general solid api design https://github.com/go-cq/cq & https://github.com/jmcvetta/neoism

I have had experience with https://github.com/jmcvetta/neoism and https://labix.org/mgo

> So for these reasons, writing a lot of unit tests is perhaps best left for later.

agree with I meant unit tests for 'permanent' code structures
