### ISSUE TITLE
Planning to support LINKBAG anytime soon?

### ISSUE THREAD

**Issue by larryaasen** [quux00/ogonori#3]
Hi,

I am glad to see support for OrientDB in Go and appreciate this client being created for everyone to use.

I am getting an error using obinary.SQLQuery() related to LINKBAG that I cannot resolve:
panic: ORecordSerializerV0#readDataValue LINKBAG NOT YET IMPLEMENTED

I would like to know if you plan to support LINKBAG anytime soon?

Thanks,
Larry

**Comment by quux00** [comment]
Hi Larry,

I've read the documentation (such as it is) that I can find on LINKBAG/RidBag and it is still a bit of a mystery to me.  Can you send me some examples of how you are using it?  Either in Java, Go or SQL.  That would help me a lot.

Once I get a better understanding of how it works, I can put in some support on the Deserialization side - meaning insofar as OrientDB allows you to use LINKBAGs with SQL, then I can probably support it sooner rather than later.  They will be more complicated than other forms since there is this interesting transition from EMBEDDED to pointer to a tree structure on the server side.  I'll need to spend some quality time reading the Java code base to work through how that works.

Adding support on the serialization side (meaning client side objects that are "saved" rather than using SQL) will take longer, as I have yet to get serialization for the basic types started.  And then I need to work out what the ogonori API will look like.

**Comment by larryaasen** [comment]
Michael,

Again I want to thank you for creating this Go client project for OrientDB. It works well for everything I have tried so far.
Today I finally tried to create some edges. Using SQLCommand() worked fine. It was when I queried one of the vertexes that was in the edge is where it failed.
First I update to the latest code in ogonori. Then I created two vertex classes, created an edge class, created a vertex for each vertex class, created an edge between those two vertexes, and then queried the first vertex class. That is when it failed. Here is the trace that might be helpful:
```
panic: ORecordSerializerV0#readDataValue LINKBAG NOT YET IMPLEMENTED

goroutine 1 [running]:
github.com/quux00/ogonori/obinary.ORecordSerializerV0.readDataValue(0xc2080102a0, 0xc2080e4150, 0x16, 0x0, 0x0, 0x0, 0x0)
	/Users/larry/Projects/go/src/github.com/quux00/ogonori/obinary/binserde.go:543 +0x1808
github.com/quux00/ogonori/obinary.ORecordSerializerV0.Deserialize(0xc2080102a0, 0xc2080412c0, 0xc2080e4150, 0x0, 0x0)
	/Users/larry/Projects/go/src/github.com/quux00/ogonori/obinary/binserde.go:76 +0x549
github.com/quux00/ogonori/obinary.(*ORecordSerializerV0).Deserialize(0x5b4b48, 0xc2080102a0, 0xc2080412c0, 0xc2080e4150, 0x0, 0x0)
	<autogenerated>:1 +0xc7
github.com/quux00/ogonori/obinary.createDocumentFromBytes(0xc2080bcfd8, 0x4, 0xc200000002, 0xc208070780, 0x1cb, 0x1cb, 0xc2080102a0, 0xc208041270, 0x0, 0x0)
	/Users/larry/Projects/go/src/github.com/quux00/ogonori/obinary/document.go:25 +0x2af
github.com/quux00/ogonori/obinary.readResultSet(0xc2080102a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/larry/Projects/go/src/github.com/quux00/ogonori/obinary/qrycmd.go:719 +0xb65
github.com/quux00/ogonori/obinary.SQLQuery(0xc2080102a0, 0xc2080648d0, 0x21, 0x0, 0x0, 0xc2080c4968, 0x1, 0x1, 0x0, 0x0, ...)
	/Users/larry/Projects/go/src/github.com/quux00/ogonori/obinary/qrycmd.go:125 +0x1080
```

Hope this helps.

Larry

**Comment by quux00** [comment]
Thanks for the note - glad to have you as an early pre-alpha tester :-)

So you are **not** explicitly creating a LINKBAG property?

If possible could you send the DDL (create vertex, etc.) you are using or the full code snippet and then the query SQL string that is failing?  If not, I can try to recreate what you are doing from your outline.

-Michael

**Comment by larryaasen** [comment]
No, I did not try to create a LINKBAG. I am not sure how it was created, but maybe when I used create edge it did that. Sorry, but I refactored all of my code to use a vertex instead of an edge for now, so I don't have the DDL. I could put it back to get the DDL, but is there an easy way to capture the DDL?

**Comment by quux00** [comment]
Once I finish the current feature I'm working on, I'll make an attempt at recreating your scenario.  You've told me something I didn't know which is that a LINKBAG can get created under the hood when working with graph nodes, so hopefully I can figure it out later this week.

It is possible to create a linkbag directly, I've done it like so (on my "Cat" class):

    CREATE PROPERTY Cat.friends LINKBAG

But my attempts to add any LINKs to the LINKBAG (in the OrientDB console) failed.  However, I didn't try very hard yet, but I didn't find any ready documentation on how to do that.  If you find any let me know.

For "capturing" the DDL, I'm not totally sure what you mean.  I just mean write down all the "CREATE xyz" statements.  You can also do a `info class XXX` in the OrientDB console client.  You can also create a script with your DDL and play those into the OrientDB console client to set up the classes/vertices/edges.  Then do the query in Go/ogonori and send those to me along with the error report.

**Comment by quux00** [comment]
Just did a commit with first support for LINKBAG retrieval from SQLQueries.
    
The codebase only supports embedded LINKBAGs at present. Embedded is the default until the number of links increases to 80 or more, at which point it changes to an pointer to external (server-side) tree-based structure.  Support for that is not yet present, nor for serializing LINKBAGs.

I was able to get LINKBAGs created in the way you outlined.   I plan on working to support the tree-based external LINKBAG next.

**Comment by larryaasen** [comment]
I pulled your latest code and ran some tests to narrow down my issue. I am getting a different error message now. Here is my script that I run from the console:
DROP DATABASE remote:localhost/mydatabase root moonwink;
CREATE DATABASE remote:localhost/mydatabase root moonwink plocal graph;
create class User extends V;
create class Following extends E
create vertex User content {"id":1};
create vertex User content {"id":2};
create edge Following from #11:0 to #11:1;
create edge Following from #11:1 to #11:0;

Here is the one line I run using ogonori:
SELECT FROM User SKIP 0 LIMIT 100;

That SELECT gives this error:
panic: TreeBasedLinkBag not yet supported

When I remove this last create edge statement, it works fine:
create edge Following from #11:1 to #11:0;

**Comment by quux00** [comment]
Hi Larry,

Thanks for the detailed note.  I've been working on the remote tree-based LinkBag the last few evenings.  The documentation around it is rather incomplete, so I've been working through the Java code to determine how to get it supported.  As a bonus I found a whole other binary serialization subsystem that I've not seen documented before. Winner winner!

In any case, I'll have some basic support for tree-based LinkBags later this week.  It won't support iterators yet (I still have to design how I want to support those), but it will pull back remote links.  I'll make sure your example works before I push it.

**Comment by larryaasen** [comment]
Michael,

Thanks for working on this feature. I see you have made some good progress with the last few commits. I am available to test out the feature whenever you are ready.

Larry

**Comment by quux00** [comment]
OK. Working on one more aspect of it today.  When I push the commit where it's working (insofar as I understand the use cases) I'll post a note here with some documentation on how to use it.

**Comment by quux00** [comment]
I've pushed another commit on this that now, so you can try to use it.  However, due to either a bug in OrientDB server or (what I consider to be) poor design in the binary network protocol, I've discovered that I need to fairly significantly rewrite parts of the deserialization internals of ogonori.  Your example actually exposed this, so thanks for that.  So for now, Document DB SQL and links will probably work fine, but queries of Graph DB structures will sporadically fail until I make the deserialization changes.

So for now, here's a quick run down of how to deal with LinkBags.  This example is in the `addManyLinksToFlipFriendLinkBagToExternalTreeBased` function of `client.go`.

When you do a query of graph vertexes, such as:

    SELECT from Person where any() traverse(0,2) (firstName = 'Abbie')

The Edge link fields will be LinkBags:

    docs, err := obinary.SQLQuery(dbc, sql, "")
    abbieVtx := docs[0]
    abbieInFriendLinkBag := abbieVtx.GetField("in_Friend").Value.(*oschema.OLinkBag)
    abbieOutFriendLinkBag := abbieVtx.GetField("out_Friend").Value.(*oschema.OLinkBag)

The links of the LinkBag may or may not be filled in, depending on whether the LinkBag was embedded or remote tree-based.  You can check with the `IsRemote` method on `OLinkBag`,   If that returns false, then the links will already be in the `OLinkBag#Links` field.  If `IsRemote` returns true, then you need to make another call to pull down all the links.   You can also check the size of the links before pulling them all down:

    if abbieOutFriendLinkBag.IsRemote() {
        sz, err := obinary.FetchSizeOfRemoteLinkBag(dbc, abbieOutFriendLinkBag)
        Ok(err)
        Equals(nAbbieOutFriends+1, sz)

        inclusive := true
        err = obinary.FetchEntriesOfRemoteLinkBag(dbc, abbieOutFriendLinkBag, inclusive)
        Ok(err)
        Equals(89, len(abbieOutFriendLinkBag.Links))
    }

Right now I'm not sure what the `inclusive` field is for.  Both true and false return the same for the use cases I tried, but it is required in the binary network request.

Finally, after calling `FetchEntriesOfRemoteLinkBag`, only the RIDs of the Links will be filled in, not the Records (ODocuments).  If you want the full records, you can then call:

    err = obinary.ResolveLinks(dbc, abbieOutFriendLinkBag.Links)

**Comment by larryaasen** [comment]
This looks very good. I will give it a try.

**Comment by larryaasen** [comment]
Thanks. I pulled the latest code and ran some tests and most have passed. In one case I get an error when I use this query. The same query works fine in the OrientDB Console.

runSQLQuery: param #14:0, sql: SELECT FROM Post WHERE @RID=?

OrientDB.runSQLQuery: github.com/quux00/ogonori/obinary/qrycmd.go:125; cause: github.com/quux00/ogonori/obinary/qrycmd.go:726; cause: github.com/quux00/ogonori/obinary/binserde.go:740; cause: github.com/quux00/ogonori/obinary/rw/reader.go:89; cause: EOF, SELECT FROM Post WHERE @RID=?

I don't have the minimal DDL for you yet because I need to time to eliminate all of the extras. I will get that for you soon.

**Comment by quux00** [comment]
That `cause: EOF` error is the one where I need to refactor how I handle the deserialization.  Because the OrientDB sometimes puts additional meaningless bytes in the output of a RidBag, my deserialization code gets confused because I made an assumption that the server wouldn't put extra nonsense bytes in.  I need to change how I parse it by following data pointers internal to the serialized format.  That will probably take me a while, but it's what I'm working on next.

**Comment by larryaasen** [comment]
Would this error be for the same reason as above?
```
OrientDB.runSQLQuery: github.com/quux00/ogonori/obinary/qrycmd.go:125; cause:
github.com/quux00/ogonori/obinary/qrycmd.go:726; cause:
github.com/quux00/ogonori/obinary/binserde.go:693; cause:
Incorrect number of bytes read from connection.
Expected: 8; Actual: 2, SELECT FROM User WHERE id=1
```

**Comment by quux00** [comment]
No, probably not, but I'd have to see the full context.  I'll be pushing a bunch of changes later today.  Try it again with those changes and if you still get that, definitely let me know with context of the queries you are doing.

**Comment by quux00** [comment]
OK, I've pushed the latest batch of commits.  I had to create a seekable byte buffer (of limited functionality) in order to robustly parse the binary serialization format that has spurious extra bytes occasionally.  So far it looks like it works, so try all your tests again.

**Comment by larryaasen** [comment]
I forgot to mention this the other day that I tested the new code and it works flawlessly. I am very grateful to you for this update. Thanks.

**Comment by quux00** [comment]
Cool.  Thanks for the feedback.  I'll close this issue.
